# Generated by Django 4.1.3 on 2022-11-27 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsblog',
            name='img',
        ),
    ]
