# Generated by Django 4.1.3 on 2022-11-27 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_newsblog_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsblog',
            name='img',
            field=models.ImageField(default=0, upload_to='main'),
            preserve_default=False,
        ),
    ]
